// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "svenrisse0@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/books": {
            "post": {
                "description": "create book with fields",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Create a Book",
                "parameters": [
                    {
                        "description": "Add book",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_svenrisse_bookshelf_internal_models.Book"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_svenrisse_bookshelf_internal_models.Book"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/tokens/authentication": {
            "post": {
                "description": "create a token for an account necessary for using certain endpoints\naccount needs to be created, and activated!",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Create a bearer token",
                "parameters": [
                    {
                        "description": "Add book",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_svenrisse_bookshelf_internal_models.CreateToken"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_svenrisse_bookshelf_internal_models.Token"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_svenrisse_bookshelf_internal_models.Book": {
            "description": "Book information",
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "J.R.R. Tolkien"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Fantasy",
                        "Epic",
                        "Children's literature"
                    ]
                },
                "pages": {
                    "type": "integer",
                    "example": 320
                },
                "title": {
                    "type": "string",
                    "example": "The Hobbit"
                },
                "year": {
                    "type": "integer",
                    "example": 1937
                }
            }
        },
        "github_com_svenrisse_bookshelf_internal_models.CreateToken": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@example.net"
                },
                "password": {
                    "type": "string",
                    "example": "pa55word"
                }
            }
        },
        "github_com_svenrisse_bookshelf_internal_models.Token": {
            "description": "Token information",
            "type": "object",
            "properties": {
                "expiry": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "bookshelf.svenrisse.com",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Bookshelf API",
	Description:      "This is the API for the Bookshelf application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
